import Page from '../components/Page'
import styles from './Legal.module.css'

export default function Privacy() {
  return (
    <Page>
      <div className={styles.container}>
        <h1 className={styles.title}>Privacy Policy</h1>
        <p className={styles.lastUpdated}>Last Updated: June 2026</p>

        <section className={styles.section}>
          <h2>1. Data Sovereignty & Philosophy</h2>
          <p>
            As a researcher focused on decentralized networks and self-hosted infrastructure, I strongly believe in data sovereignty. This portfolio is designed to be privacy-first.
          </p>
        </section>

        <section className={styles.section}>
          <h2>2. No Tracking or Cookies</h2>
          <p>
            This website does not use cookies, nor does it employ third-party analytics trackers, tracking pixels, or fingerprinting scripts. Your visit is your own business.
          </p>
        </section>

        <section className={styles.section}>
          <h2>3. Information Collection</h2>
          <p>
            The only information collected is standard server request logs (IP address, user agent, requested URL) generated by the hosting provider necessary for security and routing purposes.
          </p>
        </section>

        <section className={styles.section}>
          <h2>4. External Links</h2>
          <p>
            This site contains links to external websites (GitHub, X, etc.). Once you leave this site, you are subject to the privacy policies of those respective platforms.
          </p>
        </section>
      </div>
    </Page>
  )
}
